name: Docker Push to Dockerhub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:

  pipeline:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: docker login 
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      
      - name: Tag and push image
        env:
          REGISTRY: pedrofmm
          REPOSITORY: desafio-ssa
          IMAGE_TAG: prod-${{ github.run_number }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$REGISTRY/$REPOSITORY:$IMAGE_TAG"

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.0.0
        with:
          app_name: clownfish-app
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
                    {
                        "name":"pedrofmm-desafio-ssa",
                        "image":{
                          "registry_type":"pedrofmm",
                          "registry":"pedrofmm",
                          "repository":"desafio-ssa",
                          "tag":"prod-${{ github.run_number }}"
                        }
                    }
                  ]'
#